export const CLIENTDETAIL = "CLIENTDETAIL";
export const CLIENTID = "CLIENTID";
export const CLIENTAPPOINTMENT_DETAILS = "CLIENTAPPOINTMENT_DETAILS";
export const APPOINTMENT_FEEDBACK = "APPOINTMENT_FEEDBACK";
export const BOOKAPPOINTMENTDATA = "BOOKAPPOINTMENTDATA";
export const SWITCHCOMPONENT = "SWITCHCOMPONENT";
export const BOOKAPPOINTMENTDETAIL = "BOOKAPPOINTMENTDETAIL";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
